# Generated by Django 6.0.5 on 2026-05-15 12:04

import django.core.validators
import django.db.models.deletion
import parcels.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=parcels.models.generate_tracking_number, editable=False, max_length=32, unique=True)),
                ('sender_full_name', models.CharField(max_length=100)),
                ('sender_phone', models.CharField(max_length=20)),
                ('receiver_full_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('30.00'))])),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('in_transit', 'In transit'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['city', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ParcelStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('in_transit', 'In transit'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('returned', 'Returned')], max_length=20)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='parcels.parcel')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='parcels.postoffice')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='parcel',
            name='destination_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_parcels', to='parcels.postoffice'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sender_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_parcels', to='parcels.postoffice'),
        ),
    ]
